// <auto-generated />
namespace Consultorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class teste0036 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teste0036));
        
        string IMigrationMetadata.Id
        {
            get { return "201909100337023_teste 0036"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
