// <auto-generated />
namespace Consultorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resetandoobancodedados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resetandoobancodedados));
        
        string IMigrationMetadata.Id
        {
            get { return "201904142245329_resetando o banco de dados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
